"""Add coupon_details to GameSession

Revision ID: 04a94583521b
Revises: 368988bfe58e
Create Date: 2025-05-08 01:06:14.885002

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "04a94583521b"
down_revision = "368988bfe58e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("game_session", schema=None) as batch_op:
        batch_op.add_column(sa.Column("coupon_details", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("game_session", schema=None) as batch_op:
        batch_op.drop_column("coupon_details")

    # ### end Alembic commands ###
