"""Add session_id to BetHistory

Revision ID: 06bb689ae624
Revises: 30994f63f77d
Create Date: 2025-05-08 00:10:06.666935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06bb689ae624'
down_revision = '30994f63f77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_bet_history_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bet_history_session_id'))
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
