"""Add Notification model

Revision ID: 0c8b5730f13e
Revises: 04a94583521b
Create Date: 2025-05-08 03:18:57.750845

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0c8b5730f13e"
down_revision = "04a94583521b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("link", sa.String(length=512), nullable=True),
        sa.Column("icon", sa.String(length=100), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notification_category"), ["category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notification_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notification_is_read"), ["is_read"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notification_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_user_id"))
        batch_op.drop_index(batch_op.f("ix_notification_is_read"))
        batch_op.drop_index(batch_op.f("ix_notification_created_at"))
        batch_op.drop_index(batch_op.f("ix_notification_category"))

    op.drop_table("notification")
    # ### end Alembic commands ###
