"""Add privacy settings to User model

Revision ID: 1a799ad55272
Revises: accf824e3632
Create Date: 2025-05-09 14:26:47.991934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a799ad55272'
down_revision = 'accf824e3632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privacy_profile_public', sa.Boolean(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('privacy_show_activity', sa.Boolean(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('privacy_show_bet_history', sa.Boolean(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('privacy_show_online_status', sa.Boolean(), nullable=False, server_default=sa.text('1')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('privacy_show_online_status')
        batch_op.drop_column('privacy_show_bet_history')
        batch_op.drop_column('privacy_show_activity')
        batch_op.drop_column('privacy_profile_public')

    # ### end Alembic commands ###
