"""Add PrivateMessage model

Revision ID: 30994f63f77d
Revises: 83ade986b674
Create Date: 2025-05-07 13:18:32.908530

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "30994f63f77d"
down_revision = "83ade986b674"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "private_message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("recipient_id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("body_html", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("sender_deleted", sa.Boolean(), nullable=False),
        sa.Column("recipient_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("private_message", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_private_message_recipient_id"),
            ["recipient_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_private_message_sender_id"), ["sender_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_private_message_timestamp"), ["timestamp"], unique=False
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("last_seen")

    with op.batch_alter_table("private_message", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_private_message_timestamp"))
        batch_op.drop_index(batch_op.f("ix_private_message_sender_id"))
        batch_op.drop_index(batch_op.f("ix_private_message_recipient_id"))

    op.drop_table("private_message")
    # ### end Alembic commands ###
