"""Add GameSession, Sport, SportEvent, SportOutcome models

Revision ID: 368988bfe58e
Revises: 06bb689ae624
Create Date: 2025-05-08 00:20:14.867005

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "368988bfe58e"
down_revision = "06bb689ae624"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sport",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("group", sa.String(length=100), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("last_checked", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "sport_event",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("sport_key", sa.String(length=100), nullable=False),
        sa.Column("commence_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("home_team", sa.String(length=100), nullable=True),
        sa.Column("away_team", sa.String(length=100), nullable=True),
        sa.Column("last_update_api", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["sport_key"],
            ["sport.key"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sport_event", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sport_event_commence_time"), ["commence_time"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sport_event_sport_key"), ["sport_key"], unique=False
        )

    op.create_table(
        "game_session",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("game_mode", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("event_id", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["sport_event.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("game_session", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_game_session_creator_id"), ["creator_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_game_session_event_id"), ["event_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_game_session_status"), ["status"], unique=False
        )

    op.create_table(
        "sport_outcome",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.String(length=255), nullable=False),
        sa.Column("bookmaker", sa.String(length=100), nullable=False),
        sa.Column("market_key", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("point", sa.Float(), nullable=True),
        sa.Column("last_update_api", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["sport_event.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sport_outcome", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sport_outcome_event_id"), ["event_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sport_outcome", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sport_outcome_event_id"))

    op.drop_table("sport_outcome")
    with op.batch_alter_table("game_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_game_session_status"))
        batch_op.drop_index(batch_op.f("ix_game_session_event_id"))
        batch_op.drop_index(batch_op.f("ix_game_session_creator_id"))

    op.drop_table("game_session")
    with op.batch_alter_table("sport_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sport_event_sport_key"))
        batch_op.drop_index(batch_op.f("ix_sport_event_commence_time"))

    op.drop_table("sport_event")
    op.drop_table("sport")
    # ### end Alembic commands ###
