"""Upgrade forum models with timestamps, post links, editing info

Revision ID: 55b6ddef75d2
Revises: 91079519e0c0
Create Date: 2025-05-02 13:31:52.853180

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "55b6ddef75d2"
down_revision = "91079519e0c0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("forum_category", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sort_order", sa.Integer(), nullable=True))

    with op.batch_alter_table("forum_post", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("last_edited_by", sa.String(length=80), nullable=True)
        )
        batch_op.add_column(
            sa.Column("last_edited_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.drop_index("ix_forum_post_updated_at")

    with op.batch_alter_table("forum_thread", schema=None) as batch_op:
        batch_op.add_column(sa.Column("first_post_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("last_post_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_thread_first_post",
            "forum_post",
            ["first_post_id"],
            ["id"],
            use_alter=True,
        )
        batch_op.create_foreign_key(
            "fk_thread_last_post",
            "forum_post",
            ["last_post_id"],
            ["id"],
            use_alter=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("forum_thread", schema=None) as batch_op:
        batch_op.drop_constraint("fk_thread_last_post", type_="foreignkey")
        batch_op.drop_constraint("fk_thread_first_post", type_="foreignkey")
        batch_op.drop_column("last_post_id")
        batch_op.drop_column("first_post_id")

    with op.batch_alter_table("forum_post", schema=None) as batch_op:
        batch_op.create_index("ix_forum_post_updated_at", ["updated_at"], unique=False)
        batch_op.drop_column("last_edited_at")
        batch_op.drop_column("last_edited_by")

    with op.batch_alter_table("forum_category", schema=None) as batch_op:
        batch_op.drop_column("sort_order")

    # ### end Alembic commands ###
