"""Add post_count column to ForumThread

Revision ID: 7b8b7f859b2f
Revises: 55b6ddef75d2
Create Date: 2025-05-03 18:42:27.793409

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7b8b7f859b2f"
down_revision = "55b6ddef75d2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("forum_thread", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("post_count", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.create_index(
            batch_op.f("ix_forum_thread_post_count"), ["post_count"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("forum_thread", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_forum_thread_post_count"))
        batch_op.drop_column("post_count")

    # ### end Alembic commands ###
