"""Add Badge and BetHistory models and user associations

Revision ID: 83ade986b674
Revises: e05207bda402
Create Date: 2025-05-06 20:53:37.044556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ade986b674'
down_revision = 'e05207bda402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bet_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('match_name', sa.String(length=255), nullable=True),
    sa.Column('outcome_name', sa.String(length=255), nullable=True),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('payout', sa.Float(), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bet_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bet_history_user_id'), ['user_id'], unique=False)

    op.create_table('invite_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=36), nullable=False),
    sa.Column('created_by_username', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('uses_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('used_by_username', sa.String(length=80), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_username'], ['user.username'], ),
    sa.ForeignKeyConstraint(['used_by_username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invite_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_code_code'), ['code'], unique=True)

    op.create_table('user_badge_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badge.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'badge_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_badge_association')
    with op.batch_alter_table('invite_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_code_code'))

    op.drop_table('invite_code')
    with op.batch_alter_table('bet_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bet_history_user_id'))

    op.drop_table('bet_history')
    op.drop_table('badge')
    # ### end Alembic commands ###
