"""Initial database setup for forum.

Revision ID: 91079519e0c0
Revises:
Create Date: 2025-05-02 01:50:27.232036

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "91079519e0c0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forum_category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("forum_category", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_forum_category_name"), ["name"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_forum_category_slug"), ["slug"], unique=True
        )

    op.create_table(
        "forum_thread",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_sticky", sa.Boolean(), nullable=True),
        sa.Column("is_locked", sa.Boolean(), nullable=True),
        sa.Column("view_count", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("author_username", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["forum_category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("forum_thread", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_forum_thread_author_username"),
            ["author_username"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_forum_thread_category_id"), ["category_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_forum_thread_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_forum_thread_is_sticky"), ["is_sticky"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_forum_thread_title"), ["title"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_forum_thread_updated_at"), ["updated_at"], unique=False
        )

    op.create_table(
        "forum_post",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("body_html", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("thread_id", sa.Integer(), nullable=False),
        sa.Column("author_username", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["forum_thread.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("forum_post", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_forum_post_author_username"),
            ["author_username"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_forum_post_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_forum_post_thread_id"), ["thread_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_forum_post_updated_at"), ["updated_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("forum_post", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_forum_post_updated_at"))
        batch_op.drop_index(batch_op.f("ix_forum_post_thread_id"))
        batch_op.drop_index(batch_op.f("ix_forum_post_created_at"))
        batch_op.drop_index(batch_op.f("ix_forum_post_author_username"))

    op.drop_table("forum_post")
    with op.batch_alter_table("forum_thread", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_forum_thread_updated_at"))
        batch_op.drop_index(batch_op.f("ix_forum_thread_title"))
        batch_op.drop_index(batch_op.f("ix_forum_thread_is_sticky"))
        batch_op.drop_index(batch_op.f("ix_forum_thread_created_at"))
        batch_op.drop_index(batch_op.f("ix_forum_thread_category_id"))
        batch_op.drop_index(batch_op.f("ix_forum_thread_author_username"))

    op.drop_table("forum_thread")
    with op.batch_alter_table("forum_category", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_forum_category_slug"))
        batch_op.drop_index(batch_op.f("ix_forum_category_name"))

    op.drop_table("forum_category")
    # ### end Alembic commands ###
