"""Add thread_id to PrivateMessage for threading

Revision ID: accf824e3632
Revises: 34da18a9da64
Create Date: 2025-05-09 03:02:38.427750

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "accf824e3632"
down_revision = "34da18a9da64"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("private_message", schema=None) as batch_op:
        batch_op.add_column(sa.Column("thread_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_private_message_is_read"), ["is_read"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_private_message_thread_id"), ["thread_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_pm_thread_id", "private_message", ["thread_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("private_message", schema=None) as batch_op:
        batch_op.drop_constraint("fk_pm_thread_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_private_message_thread_id"))
        batch_op.drop_index(batch_op.f("ix_private_message_is_read"))
        batch_op.drop_column("thread_id")

    # ### end Alembic commands ###
