"""Add FailedLoginAttempt model

Revision ID: d7b09e8316b4
Revises: 0c8b5730f13e
Create Date: 2025-05-08 07:24:43.446845

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d7b09e8316b4"
down_revision = "0c8b5730f13e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "failed_login_attempt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip_address", sa.String(length=100), nullable=True),
        sa.Column("username_attempt", sa.String(length=100), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("failed_login_attempt", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_failed_login_attempt_timestamp"), ["timestamp"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_failed_login_attempt_username_attempt"),
            ["username_attempt"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("failed_login_attempt", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_failed_login_attempt_username_attempt"))
        batch_op.drop_index(batch_op.f("ix_failed_login_attempt_timestamp"))

    op.drop_table("failed_login_attempt")
    # ### end Alembic commands ###
