"""Add User model and initial Forum models

Revision ID: e05207bda402
Revises: 7b8b7f859b2f
Create Date: 2025-05-06 17:19:52.828205

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e05207bda402"
down_revision = "7b8b7f859b2f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("balance", sa.Float(), nullable=False),
        sa.Column("registration_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rank", sa.String(length=50), nullable=True),
        sa.Column("invited_by", sa.String(length=80), nullable=True),
        sa.Column("avatar", sa.String(length=255), nullable=True),
        sa.Column("about_me", sa.Text(), nullable=True),
        sa.Column("about_me_last_updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("twofa_enabled", sa.Boolean(), nullable=False),
        sa.Column("twofa_secret", sa.String(length=32), nullable=True),
        sa.Column("backup_codes", sa.Text(), nullable=True),
        sa.Column("wins", sa.Integer(), nullable=False),
        sa.Column("losses", sa.Integer(), nullable=False),
        sa.Column("total_staked", sa.Float(), nullable=False),
        sa.Column("total_won", sa.Float(), nullable=False),
        sa.Column("total_lost", sa.Float(), nullable=False),
        sa.Column("largest_win", sa.Float(), nullable=True),
        sa.Column("largest_loss", sa.Float(), nullable=True),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("xp", sa.Integer(), nullable=False),
        sa.Column("xp_next_level", sa.Integer(), nullable=False),
        sa.Column("portfolio", sa.JSON(), nullable=True),
        sa.Column("stock_transactions", sa.JSON(), nullable=True),
        sa.Column("watchlist", sa.JSON(), nullable=True),
        sa.Column("dividends", sa.JSON(), nullable=True),
        sa.Column("settings", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uid"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_user_username"), ["username"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_username"))
        batch_op.drop_index(batch_op.f("ix_user_email"))

    op.drop_table("user")
    # ### end Alembic commands ###
